# action名称
name: Publish

# 当代码合并到main分支的时候，执行下列脚本
on:
  push:
    branches: [main]
# 任务
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: 检查main分支
        uses: actions/checkout@main

      - name: 设置Node.js
        uses: actions/setup-node@main
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/ # 如果不配置将影响publish

      - name: 安装依赖
        run: npm install

      - name: 构建packages
        run: npm run build

      - name: 发布NPM包
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm publish
